# Generated by Django 5.2.10 on 2026-01-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_job_status_remove_job_user_job_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
